[project]
protostar-version = "0.7.0"
lib-path = "lib"
cairo-path = ["./lib/cairo_contracts/src", "src"]

[contracts]
StarkVest = ["src/starkvest/starkvest.cairo"]

Token = ["tests/mocks/erc20.cairo"]

[test]
target = ["tests"]

[profile.devnet.deploy]
gateway-url = "http://127.0.0.1:5050/"

[profile.testnet.deploy]
network = "alpha-goerli"

[profile.mainnet.deploy]
network = "alpha-mainnet"
