[package]
name = "za_warudo"
version = "0.1.0"
authors = ["Abdelhamid Bakhta <@abdelhamidbakhta>"]
license = "MIT"
keywords = ["starknet", "vesting"]
description = "✨ 🐺 Starknet ERC20 token vesting smart contracts 💰⏳"
documentation = "https://github.com/abdelhamidbakhta/za-warudo"
homepage = "https://github.com/abdelhamidbakhta/za-warudo"
repository = "https://github.com/abdelhamidbakhta/za-warudo"

[[target.starknet-contract]]
sierra = true
casm = true
allowed-libfuncs-list.name = "experimental"

[cairo]
sierra-replace-ids = true

[dependencies]
starknet = ">=2.1.0"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.5.0" }


[tool.snforge]
exit_first = false
