[book]
authors = ["@starknet-io"]
language = "en"
multilingual = false
src = "src"
title = "Tokei Book"

[output.html]
git-repository-url = "https://github.com/starknet-io/tokei"
edit-url-template = "https://github.com/starknet-io/tokei/book/{path}"

[output.html.playground]
runnable = false
