[book]
authors = ["@abdelhamidbakhta"]
language = "en"
multilingual = false
src = "src"
title = "Tokei Book"

[output.html]
git-repository-url = "https://github.com/abdelhamidbakhta/tokei"
edit-url-template = "https://github.com/abdelhamidbakhta/tokei/book/{path}"

[output.html.playground]
runnable = false
